version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: gulp-babel
    versions:
    - 7.0.1
  - dependency-name: babel-loader
    versions:
    - 7.1.5
